; ===============================================
; LNDH Proyektong Maramihang-Yunit
; ===============================================
[platformio]
default_envs = LH_TEST   ; Default build target

; ===============================================
; Global na kumpig (inilalapat sa lahat ng [env:*])
; ===============================================
[env]
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags = 
    -DLNDH_PROJECT

;------------------------------------------------
; Pangunahing Sasakyan (PS)
;------------------------------------------------
[env:LH_PS]
platform = espressif32
board = arduino_nano_esp32
build_src_filter = 
    +<common/>
    +<LH_PS/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_PS
; upload_port = COM3
; monitor_port = COM3

;------------------------------------------------
; Malayuang Kontroler (MK)
;------------------------------------------------
[env:LH_MK]
platform = espressif32
board = arduino_nano_esp32
build_src_filter = 
    +<common/>
    +<LH_MK/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_MK
; upload_port = COM4
; monitor_port = COM4

;------------------------------------------------
; Takad Daungan (TD)
;------------------------------------------------
[env:LH_TD]
platform = espressif32
board = arduino_nano_esp32
build_src_filter = 
    +<common/>
    +<LH_TD/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_TD
; upload_port = COM5
; monitor_port = COM5

;------------------------------------------------
; Kontrol sa Lupa (KL)
;------------------------------------------------
[env:LH_KL]
platform = espressif32
board = arduino_nano_esp32
build_src_filter = 
    +<common/>
    +<LH_KL/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_KL
; upload_port = COM6
; monitor_port = COM6

; -----------------------------------------------
; Kaligirang Pansubok (sandbox!)
; -----------------------------------------------
[env:LH_TEST]
platform = espressif32
board = arduino_nano_esp32
build_src_filter = 
    +<common/>
    +<../test/subukin.cpp>  
build_flags =
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_TEST
    -DLNDH_SANDBOX
; upload_port = COM7
; monitor_port = COM7
