; ===============================================
; LNDH v2 - Proyektong Maramihang-Yunit
; ===============================================
[platformio]
default_envs = LH_TEST

; ===============================================
; Batayang kumpigurasyon para sa lahat ng yunit
; ===============================================
[env]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters =
    time
    colorize
build_flags = 
    -DLNDH_PROJECT

;------------------------------------------------
; LH_PS - Pangunahing Sasakyan
;------------------------------------------------
[env:LH_PS]
build_src_filter = 
    -<*>
    +<LH_PS/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_PS
; upload_port = COM3
; monitor_port = COM3

;------------------------------------------------
; LH_MK - Malayuang Kontroler
;------------------------------------------------
[env:LH_MK]
build_src_filter = 
    -<*>
    +<LH_MK/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_MK
; upload_port = COM4
; monitor_port = COM4

;------------------------------------------------
; LH_TD - Takad Daungan
;------------------------------------------------
[env:LH_TD]
build_src_filter = 
    -<*>
    +<LH_TD/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_TD
; upload_port = COM5
; monitor_port = COM5

;------------------------------------------------
; LH_KL - Kontrol sa Lupa
;------------------------------------------------
[env:LH_KL]
build_src_filter = 
    -<*>
    +<LH_KL/>
build_flags = 
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_KL
; upload_port = COM6
; monitor_port = COM6

;------------------------------------------------
; LH_TEST - Kaligirang Pansubok
; Default na sketch para sa mabilis na eksperimento at smoke test.
;------------------------------------------------
[env:LH_TEST]
build_src_filter = 
    -<*>
    +<../test/test.cpp>  
build_flags =
    ${env.build_flags}
    -DLNDH_ROLE=LNDH_ROLE_TEST
    -DLNDH_SANDBOX
; upload_port = COM7
; monitor_port = COM7
